=== sinstry/json-schema/module.schema.json
{
    "$id": "https://sinstry.github.io/json-schema/module.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "description": "module",
    "type": "object",
    "required": [ "id", "name" ],
    "properties": {
      "id": {
        "description": "模块标识",
        "type": "string"
      },
      "name": {
        "description": "模块名称",
        "type": "string"
      },
      "description": {
        "description": "模块描述",
        "type": "string"
      },
      "icon_slds": {
        "description": "图标",
        "type": "string"
      },
      "objects": {
        "description": "模块包含的实体对象，模块下自动生成相应菜单或入口",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "visible": {
        "type": "boolean"
      },
      "order": {
        "type": "number"
      },
      "setting_objects": {
        "description": "由系统管理员去维护数据的实体对象",
        "type": "array",
        "items": {
          "type": "object",
          "required": [ "id", "name" ],
          "properties": {
            "id": {
                "description": "节点标识",
                "type": "string"
              },
              "object": {
                "description": "对象标识",
                "type": "string"
              },
              "name": {
                "description": "对象名称",
                "type": "string"
              },
              "parent_id": {
                "description": "父级对象标识",
                "type": "string"
              },
              "permission": {
                "description": "权限设置",
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
          }
        }
      }
    }
  }

=== sinstry/json-schema/demo/module.json
{
    "$schema": "https://sinstry.github.io/json-schema/module.schema.json",
    "id": "crm",
    "name": "CRM",
    "description": "通用客户关系管理模块",
    "order": 10,
    "objects": [
        "contact",
        "company",
        "task",
        "event"
    ],
    "setting_objects": [
        {
            "id": "crm",
            "name": "客户"
        },
        {
            "id": "account_type",
            "object": "account_type",
            "name": "客户类别",
            "parent_id": "crm"
        }
    ]
}
